### ISSUE TITLE
Surprise Feature Reporting Format

### ISSUE THREAD

**Issue by ghost** [Team-G4/electron-g4#1]
Build Version:
Surprise Feature:
How to Reproduce:
What shows in DevTools [press CTRL + SHIFT + I]:
Screenshot:

Please make a new issue, and don't comment here.

**Comment by dynamyc010** [comment]
everything is broken game formatted my bios i want a refund

**Comment by ghost** [comment]
what the fuck guys 

[![Screenshot](https://i.hiitsdevin.dev/captures/hiitsdevin_new_837510.png)](https://i.hiitsdevin.dev/captures/hiitsdevin_new_837510.png)

**Comment by ghost** [comment]
please stop uwu

[![Screenshot](https://i.hiitsdevin.dev/captures/hiitsdevin_new_364551.png)](https://i.hiitsdevin.dev/captures/hiitsdevin_new_364551.png)

**Comment by MelonCola** [comment]
sci is a furry
