### ISSUE TITLE
Discord RPC is not changing regardless of Mode and/or Score

### ISSUE THREAD

**Issue by ghost** [Team-G4/electron-g4#14]
Build Version: G4X.7
Bug: Discord RPC is not changing regardless of Mode and/or Score
How to Reproduce: Launch game, press PLAY G4, and switch modes, or score higher than 1 in Easy
What shows in DevTools [press CTRL + SHIFT + I]: ![DevTools](https://i.hiitsdevin.dev/captures/hiitsdevin_new_475726.png)
Screenshot: ![Screenshot](https://i.hiitsdevin.dev/captures/hiitsdevin_new_346621.png)

**Comment by ghost** [comment]
btw, this is if you Build from the repo, so

**Comment by dynamyc010** [comment]
have you tried building with the whole node_modules folder?

**Comment by ghost** [comment]
> have you tried building with the whole node_modules folder?

yes. theres also no discord-rpc errors.

**Comment by dynamyc010** [comment]
have you tried an another machine, maybe a VM to make sure it isnt your machine specific?

**Comment by ghost** [comment]
> have you tried an another machine, maybe a VM to make sure it isnt your machine specific?

i'll try that right now

**Comment by dynamyc010** [comment]
also it might be Discord's API taking a dump

**Comment by ghost** [comment]
> also it might be Discord's API taking a dump

i really hope that's not the case.

**Comment by ghost** [comment]
> also it might be Discord's API taking a dump

Yeah, looks like it was just Discord API taking a dump last night. Closing bug report .-.

Sorry if I wasted your time
