### ISSUE TITLE
current BiquadNode is null: assets.js:16

### ISSUE THREAD

**Issue by justchen1369** [Team-G4/electron-g4#15]
`**let currentBiquadNode = null**
let isAudioPlaying = false
let audioStartTime = 0

/**
 * @param {AudioContext} audioCtx 
 * @param {String} audioFile 
 */
async function loadAudioBuffer(audioCtx, audioFile) {
    let data = await fetch(audioFile)
    let arrayBuf = await data.arrayBuffer()

    return await audioCtx.decodeAudioData(arrayBuf)
}

function stopAudio() {
    currentSourceNode.disconnect(currentBiquadNode)
    **currentBiquadNode.disconnect(audioCtx.destination)**
    currentSourceNode.stop()
}

function enableSlowAudioEffect() {
    **currentBiquadNode.frequency.linearRampToValueAtTime(1000, 1)**
    currentSourceNode.playbackRate.linearRampToValueAtTime(0.5, 1)
}`

**Comment by ghost** [comment]
I would request that you use the Bug Reporting Format next time please?

And what's going on

**Comment by justchen1369** [comment]
![image](https://user-images.githubusercontent.com/35386456/70922552-49de2d00-1ff4-11ea-8264-ea26b2387bb2.png)
it is declared as null and never changed to something else.

This happens when audio attempts to play while in slowmode.

**Comment by scidsgn** [comment]
yeet, a leftover from the old audio code

**Comment by justchen1369** [comment]
on a related note, we need a user gesture before declaring a new audioContext(assets.js:8)

**Comment by justchen1369** [comment]
any comments? I will close this otherwise due to it being a separate issue.
