### ISSUE TITLE
oops, a bunch of 404s!

### ISSUE THREAD

**Issue by justchen1369** [Team-G4/electron-g4#16]
Web Release
![image](https://user-images.githubusercontent.com/35386456/71021680-e116b380-20cc-11ea-9746-3fa31fec3bcb.png)

**Comment by ghost** [comment]
wrong repo, go to https://GitHub.com/Team-G4/base-g4

**Comment by justchen1369** [comment]
closing.

**Comment by dynamyc010** [comment]
@HiItsDevin you could've just transferred the issue too though

**Comment by ghost** [comment]
> @HiItsDevin you could've just transferred the issue too though

was in the FastHub app at the time, sorry

**Comment by dynamyc010** [comment]
> > @HiItsDevin you could've just transferred the issue too though
> 
> was in the FastHub app at the time, sorry

ah aight
