### ISSUE TITLE
Player Reporting Format

### ISSUE THREAD

**Issue by ghost** [Team-G4/electron-g4#18]
Player Name:
Screenshot Proof **[click on the Player's name to open Player Stats]**: 
When did you find out they cheated: 

Only report if you are certain, and seems very suspicious

**Comment by dynamyc010** [comment]
ok uh how do you think this'll work? what if that guy legitly got a 300 after idfk how many hours of play, and you just VL'd the poor fella? :c
Speaking of poor fellas, time to check on Side Dish, brb

**Comment by ghost** [comment]
> ok uh how do you think this'll work? what if that guy legitly got a 300 after idfk how many hours of play, and you just VL'd the poor fella? :c
> Speaking of poor fellas, time to check on Side Dish, brb

let me add "only report if you are certain, and seems very suspicious"
