### ISSUE TITLE
Pressing Tab Multiple Times Breaks G4X.7

### ISSUE THREAD

**Issue by EdwardJXLi** [Team-G4/electron-g4#2]
Build Version: Public Beta 1
Bug: Pressing Tab Multiple Times Breaks G4X.7
How to Reproduce: Spam TAB, or press TAB in the middle of opening another window
What shows in DevTools [press CTRL + SHIFT + I]: Nothing Out Of The Ordinary
Screenshot: 
https://cdn.discordapp.com/attachments/633000277749792803/653045246346788895/unknown.png

**Comment by ghost** [comment]
Can confirm that this somehow breaks the game, if you do it while G4X is loading, "PLAY G4" button just simply does not work.

**Comment by scidsgn** [comment]
you have caught my attention, i have now intensified

**Comment by scidsgn** [comment]
it no longer does, fake news as of 2:08 pm poland time
