### ISSUE TITLE
owo bug wepowt // Shook mode being a shookingly bad

### ISSUE THREAD

**Issue by dynamyc010** [Team-G4/electron-g4#3]
Build Version: G4X.7 PB1
Bug: shook mode broke sis
How to Reproduce: 1. turn on light mode
2. try to open shook mode
3. see the game do absolutely nothing. yes.
What shows in DevTools [press CTRL + SHIFT + I]: https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_435768.png
Screenshot: https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_435768.png

**Comment by scidsgn** [comment]
indeed, everyone's wigs are in fact shooketh to Saturn due to the fact that i forgot to make light mode shook mode (shooketh)

**Comment by ghost** [comment]
> indeed, everyone's wigs are in fact shooketh to Saturn due to the fact that i forgot to make light mode shook mode (shooketh)

ouch, oh well, time to get fixing
