### ISSUE TITLE
owo anowher bwug wepowt // shook mode is being reported undefined in some places.

### ISSUE THREAD

**Issue by dynamyc010** [Team-G4/electron-g4#4]
Build Version: G4X.7 PB1
Bug: shook mode reported as undefined (I know that RPC is my work, getting on it right away boss)
How to Reproduce: uh... open g4?
What shows in DevTools [press CTRL + SHIFT + I]: https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_513288.png
Screenshot:
https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_602012.png
https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_358547.png
https://dynamyc010.hiitsdevin.dev/captures/dynamyc010_441387.png

**Comment by dynamyc010** [comment]
Fixed the RPC part, leaderboards and stuff is still Undefined.

**Comment by dynamyc010** [comment]
I'm guessing that's a problem in base

**Comment by scidsgn** [comment]
> I'm guessing that's a problem in base

fixed in base, pushing a change to this repo in a momento
