### ISSUE TITLE
what the fuck guys

### ISSUE THREAD

**Issue by dynamyc010** [Team-G4/electron-g4#6]
what the fuck guys 

[![Screenshot](https://i.hiitsdevin.dev/captures/hiitsdevin_new_837510.png)](https://i.hiitsdevin.dev/captures/hiitsdevin_new_837510.png)

_Originally posted by @HiItsDevin in https://github.com/Team-G4/g4x/issues/1#issuecomment-562976611_

**Comment by ghost** [comment]
y e e t

**Comment by dynamyc010** [comment]
Sad
